---
- name: Rename Computer
  ansible.windows.win_hostname:
    name: "{{ host_name }}"
  register: res

- name: Reboot after rename
  ansible.windows.win_reboot:
  when: res.reboot_required

- name: Join Domain
  ansible.windows.win_domain_membership:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_user: "{{ domain_admin}}@{{ domain_name }}"
    domain_admin_password: "{{ admin_pass }}"
    domain_ou_path: "{{ path }}"
    state: domain
  register: domain_state

- name: Reboot after joining domain
  ansible.windows.win_reboot:
  when: domain_state.reboot_required