---
- hosts: localhost
  name: Deploy Lab
  tasks:

- name: Deploy Lab Infrastructure
  import_playbook: ansible/1-Deploy-Infrastructure.yml

- name: Pause for a 3 minutes to let sysprep finish
  import_playbook: ansible/pause.yml

- name: Configure Windows Forest DC
  hosts: 192.168.1.10
  roles:
    - forest-dc

- name: Configure Windows Clients
  hosts: wks
  roles: 
    - domain-member
    - common-win
    - wsl

