---
- name: Testing Playbooks
  vars_files:  
    - ./ansible/group_vars/users.yml
    - ./ansible/group_vars/domain.yml
  hosts: 192.168.1.22 #wks
  #become: true
  #become_method: runas
  #become_user: .\Admin

  roles: 
    #- bginfo
    #- elastic_defend
    #- defender
    #- openEDR
    - limacharlie


    

    