---
#- name: Set Autologon
#  ansible.windows.win_regedit:
#    path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
#    name: AutoAdminLogon
#    data: 1
#
#
#- name: Set Autologon User
#  ansible.windows.win_regedit:
#    path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
#    name: DefaultUserName
#    data:  ajuhrukeg
#
#
#- name: Set Autologon Pass
#  ansible.windows.win_regedit:
#    path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
#    name: DefaultPassword
#    data: $1HouseWife1$
#
#
#- name: Set Autologon Pass
#  ansible.windows.win_regedit:
#    path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
#    name: DefaultDomainName
#    data: researchlab

- name: Set autologon registry files
  ansible.windows.win_powershell:
    script: |
      Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name AutoAdminLogon -Value 1
      Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name DefaultUserName -value ajuhrukeg
      Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name DefaultPassword -value '$1HouseWife1$'
      Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name DefaultDomainName -value research


- name: Reboot 
  ansible.windows.win_reboot:
