---
- name: Create Test Users
  community.windows.win_domain_user:
    name: "{{ item.username }}"
    domain_server: "{{ domain_name }}"
    domain_username: "{{ domain_admin }}"
    domain_password: "{{ admin_pass }}"
    enabled: true
    firstname: "{{ item.first_name }}"
    surname: "{{ item.last_name }}"
    email: "{{ item.email }}"
    password: "{{ item.password }}"
    password_never_expires: true
    path: "{{ users_path }}"
    sam_account_name: "{{ item.username }}"
    groups: "{{ item.department }}"
    attributes:
      displayName: "{{ item.title }} {{ item.first_name }} {{ item.last_name }}"
      title: "{{ item.title }}"
      employeeID: "{{ item.employeeID}}"
      homephone: '{{ item.phoneNum }}'
      department: "{{ item.department }}"
      description: "{{ item.job_role }}"
    state: present
  with_items: "{{ users }}"

- name: Add IT to Domain Admins
  ansible.windows.win_shell: Add-ADGroupMember -Identity "Domain Admins" -Members IT


    