---
- name: Create Test Users
  community.windows.win_domain_user:
    name: "{{ item.username }}"
    domain_server: spacewars.local
    domain_username: spacewars\Administrator
    domain_password: PassWord12#$34
    enabled: true
    firstname: "{{ item.first_name }}"
    surname: "{{ item.last_name }}"
    password: "{{ item.password }}"
    password_never_expires: true
    path: ou=spacewars-users,ou=Spacewars,dc=Spacewars,dc=local
    sam_account_name: "{{ item.username }}"
    groups: "{{ item.department }}"
    attributes:
      displayName: "{{ item.title }} {{ item.first_name }} {{ item.last_name }}"
      title: "{{ item.title }}"
      employeeID: "{{ item.employeeID}}"
      homephone: '{{ item.phoneNum }}'
      department: "{{ item.department }}"
      description: "{{ item.job_role }}"
    state: present
  with_items: "{{ users }}"

- name: Add Heros to Domain Admins
  ansible.windows.win_shell: Add-ADGroupMember -Identity "Domain Admins" -Members Hero


    