---
- name: Update RedHat OS Family
  yum: 
    name: '*'
    state: latest
    update_cache: yes
    update_only: yes
  when: ansible_os_family == "RedHat"

- name: Update Debian OS Family
  apt: 
    name: '*'
    state: latest
    update_cache: yes
    force: yes
  when: ansible_os_family == "Debian"